// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcUzTLPnLtuqqZ5-VouHpcKkUr1oMfyQ',
    appId: '1:443053062032:web:d37604dfd2e1be372f2515',
    messagingSenderId: '443053062032',
    projectId: 'e-commerce-app-3c536',
    authDomain: 'e-commerce-app-3c536.firebaseapp.com',
    storageBucket: 'e-commerce-app-3c536.appspot.com',
    measurementId: 'G-GFBTCPN8RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69QwSq_LqBU3zjWXm1MKCx5TtRasETyk',
    appId: '1:443053062032:android:4f6b92b31881b0372f2515',
    messagingSenderId: '443053062032',
    projectId: 'e-commerce-app-3c536',
    storageBucket: 'e-commerce-app-3c536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKumw935uA14Rg6TK3He_MKpbQLbwI5KA',
    appId: '1:443053062032:ios:a49caf478d36c5722f2515',
    messagingSenderId: '443053062032',
    projectId: 'e-commerce-app-3c536',
    storageBucket: 'e-commerce-app-3c536.appspot.com',
    iosBundleId: 'com.example.fruitsECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKumw935uA14Rg6TK3He_MKpbQLbwI5KA',
    appId: '1:443053062032:ios:a49caf478d36c5722f2515',
    messagingSenderId: '443053062032',
    projectId: 'e-commerce-app-3c536',
    storageBucket: 'e-commerce-app-3c536.appspot.com',
    iosBundleId: 'com.example.fruitsECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcUzTLPnLtuqqZ5-VouHpcKkUr1oMfyQ',
    appId: '1:443053062032:web:694224e7c4efe0b52f2515',
    messagingSenderId: '443053062032',
    projectId: 'e-commerce-app-3c536',
    authDomain: 'e-commerce-app-3c536.firebaseapp.com',
    storageBucket: 'e-commerce-app-3c536.appspot.com',
    measurementId: 'G-03EPWQSK37',
  );
}
